# this file lists the parameters of all bots in the swarm
# WARNING : Robot name in this file MUST BE the same as robot Hostname
# Clio parameters
- Clio :
    A: LargeMotor, 
    B: LargeMotor, 
    C: MediumMotor, 
    D: False, 
    S1: DIST-Nx-v3,
    S2: Gyro, 
    S3: Sound, 
    S4: Touch, 
    height: 200, 
    length: 250, 
    width: 150
# Erato parameters
- Erato :
    A: LargeMotor,
    B: LargeMotor,
    C: MediumMotor,
    D: false,
    S1: IRSensor,
    S2: Compass,
    S3: Sound, 
    S4: Touch, 
    height: 200, 
    length: 250, 
    width: 150
# Calliope parameters
- Calliope :
    A: LargeMotor, 
    B: false, 
    C: MediumMotor, 
    D: false, 
    S1: IRSensor,
    S2: Color, 
    S3: Sound, 
    S4: Touch, 
    height: 200, 
    length: 250, 
    width: 150