# this file lists the parameters of all bots in the swarm
# WARNING : Robot name in this file MUST BE the same as robot Hostname
# Clio parameters
Clio :
    motors:
        A: LargeMotor
        B: LargeMotor
        C: MediumMotor
        D: False
    sensors:
        in1: DIST-Nx-v3
        in2: Gyro
        in3: Sound
        in4: Touch
    dimensions:
        wheel_diameter: 200
        wheel_spacing: 250
    parameters:
        default_speed: 400
        threshold_distance: 100
# Erato parameters
Erato :
    motors:
        A: LargeMotor
        B: LargeMotor
        C: MediumMotor
        D: False
    sensors:
        in1: IRSensor
        in2: Compass
        in3: Sound
        in4: Touch
    dimensions:
        wheel_diameter: 200
        wheel_spacing: 250
    parameters:
        default_speed: 400
        threshold_distance: 100
# Calliope parameters
Calliope :
    motors:
        A: LargeMotor
        B: LargeMotor
        C: MediumMotor
        D: False
    sensors:
        in1: IRSensor
        in2: Color
        in3: Sound
        in4: Touch
    dimensions:
        wheel_diameter: 200
        wheel_spacing: 250
    parameters:
        default_speed: 400
        threshold_distance: 100